markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
title: Polslinux's Blog
#name: Polslinux's Blog
url: http://paolostivanin.github.io
intro: Where there is a shell there is a way!
permalink: /:year/:month/:title/
description: Personal Blog
paginate: 8
highlighter: pygments
disqus_shortname: paolostivanin
license:
  link: 'https://creativecommons.org/licenses/by-nc/4.0/'
  label: 'CC-BY-NC'

# Owner/author information
owner:
  name: Paolo Stivanin
  email: info@paolostivanin.com
  twitter: polslinux
  github: https://github.com/paolostivanin
  google_plus: PaoloStivanin

# Analytics and webmaster tools stuff goes here
#google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
#bing_verify:

# Links to include in top navigation
# For external links add external: true
