name: Polslinux's Blog
markdown: redcarpet
pygments: true
url: http://paolostivanin.github.io
paginate: 8
description:     Paolo Stivanin
intro: Where there is a shell there is a way!
#logo:             logo.png
disqus_shortname:
# url: http://gotchacode.com
#Comment out url when working locally to resolve base urls correctly
#url:

# Owner/author information
owner:
  name:           Paolo Stivanin
#  avatar:         <avatar-image-link>
  email:          <your-email-address>

  twitter: https://twitter.com/polslinux
  github: https://github.com/paolostivanin
  google_plus: https://plus.google.com/u/0/+PaoloStivanin

# Analytics and webmaster tools stuff goes here
#google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
#bing_verify:

# Links to include in top navigation
# For external links add external: true
