permalink: /:categories/:title.html
url: "http://paolostivanin.com"
full_name: "Paolo Stivanin"
first_name: "Paolo"
last_name: "Stivanin"
blog_title: "Polslinux's Blog "
author_img_name_path: "/images/user.jpg"
disqus_shortname: "paolostivanin"
copyright_year: "2014"
google_analytics_code: ""
aboutme: "Something about the author here"
twitter: "polslinux"
github: "paolostivanin"
facebook: "paolo.stivanin"
linkined_url: "paolo-stivanin/74/664/b75/"
