# Site settings
title: Polslinux's Blog
header-img: img/home-bg.jpg
description: "Where there is a shell there is a way!"
baseurl: ""
author: "Paolo Stivanin"
url: "http://paolostivanin.com"
linkedin_pubname : "paolo-stivanin/74/664/b75/"
twitter_username: polslinux
github_username:  paolostivanin
facebook_username:  paolo.stivanin

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
